#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidDemo.Resource", IsApplication=true)]

namespace AndroidDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04000b
			public const int black = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int color1 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int color2 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int color3 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int color4 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int color5 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int color6 = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int divider = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int grey = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int lightgrey = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int red = 2130968582;
			
			// aapt resource value: 0x7f04000c
			public const int white = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int whitedark = 2130968586;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int details = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int shawshank = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int white_bg_selector = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07003c
			public const int TableLayout01 = 2131165244;
			
			// aapt resource value: 0x7f070041
			public const int TableLayout02 = 2131165249;
			
			// aapt resource value: 0x7f070046
			public const int TableLayout03 = 2131165254;
			
			// aapt resource value: 0x7f070007
			public const int bn1 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int bn2 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int bn3 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int bn4 = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int bn5 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int bn6 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int bn7 = 2131165198;
			
			// aapt resource value: 0x7f07001d
			public const int button0 = 2131165213;
			
			// aapt resource value: 0x7f07000b
			public const int button1 = 2131165195;
			
			// aapt resource value: 0x7f070019
			public const int button2 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int button3 = 2131165210;
			
			// aapt resource value: 0x7f070015
			public const int button4 = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int button5 = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int button6 = 2131165207;
			
			// aapt resource value: 0x7f070011
			public const int button7 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int button8 = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int button9 = 2131165203;
			
			// aapt resource value: 0x7f070022
			public const int buttonAbsoluteLayout = 2131165218;
			
			// aapt resource value: 0x7f070010
			public const int buttonClear = 2131165200;
			
			// aapt resource value: 0x7f070014
			public const int buttonDivision = 2131165204;
			
			// aapt resource value: 0x7f07001c
			public const int buttonDot = 2131165212;
			
			// aapt resource value: 0x7f07001e
			public const int buttonEQ = 2131165214;
			
			// aapt resource value: 0x7f070023
			public const int buttonFrameLayout = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int buttonGridLayout = 2131165220;
			
			// aapt resource value: 0x7f070020
			public const int buttonLinearLayout = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int buttonLinearLayout2 = 2131165217;
			
			// aapt resource value: 0x7f070028
			public const int buttonMovie = 2131165224;
			
			// aapt resource value: 0x7f070026
			public const int buttonRelativeLayout = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int buttonRelativeLayout2 = 2131165223;
			
			// aapt resource value: 0x7f07001f
			public const int buttonSub = 2131165215;
			
			// aapt resource value: 0x7f070025
			public const int buttonTableLayout = 2131165221;
			
			// aapt resource value: 0x7f07001b
			public const int button_ = 2131165211;
			
			// aapt resource value: 0x7f070018
			public const int buttonx = 2131165208;
			
			// aapt resource value: 0x7f07000f
			public const int eidtText1 = 2131165199;
			
			// aapt resource value: 0x7f07002c
			public const int imageViewPicture = 2131165228;
			
			// aapt resource value: 0x7f07002a
			public const int imageViewTop = 2131165226;
			
			// aapt resource value: 0x7f070033
			public const int imageviewRightArrow = 2131165235;
			
			// aapt resource value: 0x7f070032
			public const int listViewMovie = 2131165234;
			
			// aapt resource value: 0x7f070006
			public const int myButton = 2131165190;
			
			// aapt resource value: 0x7f07003d
			public const int ok1 = 2131165245;
			
			// aapt resource value: 0x7f070048
			public const int ok10 = 2131165256;
			
			// aapt resource value: 0x7f070049
			public const int ok11 = 2131165257;
			
			// aapt resource value: 0x7f07004a
			public const int ok12 = 2131165258;
			
			// aapt resource value: 0x7f07004b
			public const int ok13 = 2131165259;
			
			// aapt resource value: 0x7f07004c
			public const int ok14 = 2131165260;
			
			// aapt resource value: 0x7f07003e
			public const int ok2 = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int ok3 = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int ok4 = 2131165248;
			
			// aapt resource value: 0x7f070042
			public const int ok5 = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int ok6 = 2131165251;
			
			// aapt resource value: 0x7f070044
			public const int ok7 = 2131165252;
			
			// aapt resource value: 0x7f070045
			public const int ok8 = 2131165253;
			
			// aapt resource value: 0x7f070047
			public const int ok9 = 2131165255;
			
			// aapt resource value: 0x7f070029
			public const int relativeLayout1 = 2131165225;
			
			// aapt resource value: 0x7f07003b
			public const int textView2 = 2131165243;
			
			// aapt resource value: 0x7f070030
			public const int txtActor = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int txtDescription = 2131165233;
			
			// aapt resource value: 0x7f07002e
			public const int txtDirector = 2131165230;
			
			// aapt resource value: 0x7f07002d
			public const int txtGrade = 2131165229;
			
			// aapt resource value: 0x7f07002b
			public const int txtName = 2131165227;
			
			// aapt resource value: 0x7f07002f
			public const int txtStory = 2131165231;
			
			// aapt resource value: 0x7f070000
			public const int view01 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int view02 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int view03 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int view04 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int view05 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int view06 = 2131165189;
			
			// aapt resource value: 0x7f070034
			public const int view07 = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int view08 = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int view09 = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int view10 = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int view11 = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int view12 = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int view13 = 2131165242;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AbsoluteLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FrameLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GridLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LinearLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int LinearLayout2 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MovieDetails = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MovieList = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MovieList_Item = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int RelativeLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int RelativeLayout2 = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int TableLayout = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int AbsoluteLayoutText = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int Description = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int FrameLayoutText = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int GridLayoutText = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int LinearLyoutText = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int LinearLyoutText2 = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int MovieDetailText = 2131034125;
			
			// aapt resource value: 0x7f050002
			public const int MovieName = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public const int MovieText = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int RelativeLayoutText = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int RelativeLayoutText2 = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int TableLayoutText = 2131034121;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int RedBackgroud = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int Theme_Custom = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int Theme_Main = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int WindowTitleStyle = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
